apiVersion: apps/v1
kind: Deployment
metadata:
  name: annnd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: annnd
  template:
    metadata:
      labels:
        app: annnd
    spec:
      containers:
      - image: okteto.dev/annnd:latest
        name: annnd
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "bddaa7f7-c473-48ac-a712-f113b0038ca2"
        - name: Vless_Path
          value: "/vl-555"
        - name: Vmess_UUID
          value: "bddaa7f7-c473-48ac-a712-f113b0038ca2"
        - name: Vmess_Path
          value: "/vm-555"
        - name: Share_Path
          value: "/v2link"
